# Site
name: "酷酷汽水的小窝"
title: "Memoirs"
description: "一万年太久，只争朝夕！"
logo: 'assets/images/chebuIco.png'
favicon: 'assets/images/chebuIco.png'
# baseurl: /
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: wowthemesnet@gmail.com

version:          1.0
gitbook_version:  3.2.3

url:              'https://sighingnow.github.io'
baseurl:          '/jekyll-gitbook'
rss:              RSS
# Authors
authors:
  sal:
    name: Tsing
    display_name: 酷酷汽水
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: moe_tsing@qq.com
    web: https://github.com/TsingWei/
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."

toc:
  enabled: true
  h_min: 1
  h_max: 3

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jemoji
